import { describe, it, expect } from "vitest";
import { decideTwoLeggedTie, decideSingleLegKO, scoreForTeam, type TieLegLite } from "../twoLeggedTie";

const A = 11;
const B = 22;

/** Leg-2 row: A is home (penalties are stored in this orientation). */
const leg2 = (aScore: number | null, bScore: number | null, penA?: number | null, penB?: number | null): TieLegLite => ({
  team_a_id: A,
  team_b_id: B,
  team_a_score: aScore,
  team_b_score: bScore,
  penalty_a: penA ?? null,
  penalty_b: penB ?? null,
  status: "finished",
});

/** Leg-1 row: teams swapped (B home), as generated by the two-leg expansion. */
const leg1 = (bScore: number | null, aScore: number | null, status: "scheduled" | "finished" = "finished"): TieLegLite => ({
  team_a_id: B,
  team_b_id: A,
  team_a_score: bScore,
  team_b_score: aScore,
  status,
});

describe("scoreForTeam", () => {
  it("reads a team's score regardless of which slot it occupies", () => {
    expect(scoreForTeam(leg1(3, 1), A)).toBe(1);
    expect(scoreForTeam(leg1(3, 1), B)).toBe(3);
    expect(scoreForTeam(leg2(2, 0), A)).toBe(2);
    expect(scoreForTeam(leg2(2, 0), 999)).toBe(0); // not in this match
  });
});

describe("decideTwoLeggedTie — decided on LEG WINS, never aggregate", () => {
  it("team winning both legs advances (via wins)", () => {
    // leg1: A beats B 2-1 (A away) — leg2: A beats B 1-0
    const res = decideTwoLeggedTie(leg2(1, 0), leg1(1, 2));
    expect(res).toEqual({ kind: "decided", winnerTeamId: A, via: "wins" });
  });

  it("one win + one draw advances the winner", () => {
    // leg1 drawn 1-1 — leg2: B wins 0-2
    const res = decideTwoLeggedTie(leg2(0, 2), leg1(1, 1));
    expect(res).toEqual({ kind: "decided", winnerTeamId: B, via: "wins" });
  });

  it("aggregate NEVER decides: 1 win each goes to penalties even at lopsided aggregate", () => {
    // leg1: A wins 0-1. leg2: B wins 5-0... wait, leg2 has A home: A 0 - 5 B.
    // Aggregate: A 1 - 7 B, but leg wins are 1-1 → penalties required.
    const noPens = decideTwoLeggedTie(leg2(0, 5), leg1(0, 1));
    expect(noPens.kind).toBe("undecided");

    const withPens = decideTwoLeggedTie(leg2(0, 5, 4, 2), leg1(0, 1));
    expect(withPens).toEqual({ kind: "decided", winnerTeamId: A, via: "penalties" });
  });

  it("both legs drawn → penalties decide", () => {
    const res = decideTwoLeggedTie(leg2(2, 2, 3, 5), leg1(0, 0));
    expect(res).toEqual({ kind: "decided", winnerTeamId: B, via: "penalties" });
  });

  it("level or missing penalties leave the tie undecided", () => {
    expect(decideTwoLeggedTie(leg2(1, 1, 4, 4), leg1(0, 0)).kind).toBe("undecided");
    expect(decideTwoLeggedTie(leg2(1, 1), leg1(0, 0)).kind).toBe("undecided");
    expect(decideTwoLeggedTie(leg2(1, 1, 4, null), leg1(0, 0)).kind).toBe("undecided");
  });

  it("penalties are read in the LEG-2 orientation (penalty_a belongs to leg2.team_a_id)", () => {
    // pa > pb → leg-2 home team (A) advances
    expect(decideTwoLeggedTie(leg2(1, 1, 5, 3), leg1(2, 2))).toEqual({
      kind: "decided",
      winnerTeamId: A,
      via: "penalties",
    });
    expect(decideTwoLeggedTie(leg2(1, 1, 3, 5), leg1(2, 2))).toEqual({
      kind: "decided",
      winnerTeamId: B,
      via: "penalties",
    });
  });
});

describe("decideTwoLeggedTie — guards", () => {
  it("pending while leg 1 is not finished (an unplayed leg must not read as 0-0)", () => {
    expect(decideTwoLeggedTie(leg2(1, 0), leg1(0, 0, "scheduled")).kind).toBe("pending");
  });

  it("pending while either leg is missing scores", () => {
    expect(decideTwoLeggedTie(leg2(1, 0), leg1(null, null)).kind).toBe("pending");
    expect(decideTwoLeggedTie(leg2(null, null), leg1(1, 0)).kind).toBe("pending");
  });

  it("single-match fallback when the decider has no teams", () => {
    const res = decideTwoLeggedTie(
      { team_a_id: null, team_b_id: B, team_a_score: 1, team_b_score: 0 },
      leg1(0, 0)
    );
    expect(res.kind).toBe("single");
  });
});

describe("decideSingleLegKO — score first, then penalties (the match-2566 case)", () => {
  const m = (aScore: number | null, bScore: number | null, penA?: number | null, penB?: number | null): TieLegLite => ({
    team_a_id: A,
    team_b_id: B,
    team_a_score: aScore,
    team_b_score: bScore,
    penalty_a: penA ?? null,
    penalty_b: penB ?? null,
    status: "finished",
  });

  it("non-level score decides via score (either direction)", () => {
    expect(decideSingleLegKO(m(2, 1))).toEqual({ kind: "decided", winnerTeamId: A, via: "score" });
    expect(decideSingleLegKO(m(0, 3))).toEqual({ kind: "decided", winnerTeamId: B, via: "score" });
  });

  it("level score + pens decides via penalties (4-4, pens 5-4)", () => {
    expect(decideSingleLegKO(m(4, 4, 5, 4))).toEqual({ kind: "decided", winnerTeamId: A, via: "penalties" });
    expect(decideSingleLegKO(m(0, 0, 2, 3))).toEqual({ kind: "decided", winnerTeamId: B, via: "penalties" });
  });

  it("level score without pens is undecided (missing-pens)", () => {
    expect(decideSingleLegKO(m(1, 1))).toEqual({ kind: "undecided", reason: "missing-pens" });
    expect(decideSingleLegKO(m(1, 1, 3, null))).toEqual({ kind: "undecided", reason: "missing-pens" });
  });

  it("level score + level pens is undecided (level-pens)", () => {
    expect(decideSingleLegKO(m(2, 2, 4, 4))).toEqual({ kind: "undecided", reason: "level-pens" });
  });

  it("stray pens on a non-level score do not change the winner (via score)", () => {
    // Callers null the stored pens when via === "score".
    expect(decideSingleLegKO(m(3, 1, 2, 4))).toEqual({ kind: "decided", winnerTeamId: A, via: "score" });
  });

  it("0 goals is a real score, not a missing one (falsy-zero)", () => {
    expect(decideSingleLegKO(m(0, 1))).toEqual({ kind: "decided", winnerTeamId: B, via: "score" });
    // pens 0-x: 0 must not be treated as missing
    expect(decideSingleLegKO(m(1, 1, 0, 2))).toEqual({ kind: "decided", winnerTeamId: B, via: "penalties" });
  });

  it("missing teams cannot be decided", () => {
    expect(decideSingleLegKO({ ...m(1, 0), team_a_id: null })).toEqual({ kind: "undecided", reason: "missing-teams" });
  });
});
