// app/layout.tsx
import type { Metadata, Viewport } from "next"; // [CTRL-1]
import "./globals.css";

import Navbar from "./lib/Navbar/Navbar";
import {
  Geist,
  Geist_Mono,
  Roboto_Condensed,
  Ubuntu_Condensed,
  Noto_Sans,
} from "next/font/google";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

// Your current body font
const robotoCondensed = Roboto_Condensed({
  subsets: ["latin", "greek"],
  weight: ["300", "400", "700"],
  variable: "--font-roboto-condensed",
  display: "swap",
});

const ubuntuCondensed = Ubuntu_Condensed({
  subsets: ["latin", "greek"],
  weight: ["400"],
  variable: "--font-ubuntu-condensed",
  display: "swap",
});

// Variable Noto Sans
const notoSans = Noto_Sans({
  subsets: ["latin", "greek"],
  weight: ["400", "700"],
  variable: "--font-noto-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ✅ Proper mobile viewport so the site is not zoomed on phones
export const viewport: Viewport = { // [CTRL-2]
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  // maximumScale: 1, // (optional) uncomment to disable pinch-zoom [CTRL-3]
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="el"> {/* [CTRL-4] */}
      {/* Note: You can keep these links here, or move them to app/head.tsx (see below) */}
      <head>
        {/* FullCalendar CSS */}
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/@fullcalendar/core@6.1.11/index.global.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@6.1.11/index.global.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/@fullcalendar/timegrid@6.1.11/index.global.min.css"
        />
      </head>
      <body
        className={[
          "antialiased",
          "font-sans", // -> your Tailwind mapping to Roboto Condensed
          robotoCondensed.variable,
          ubuntuCondensed.variable,
          notoSans.variable,
          geistSans.variable,
          geistMono.variable,
        ].join(" ")}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
